### PR TITLE
 update log4js to 2.3.x

### LINKED ISSUE #7: update to  "log4js": "1.1.0" ？
Hi：

now the dependency  log4js is 0.6 

Is there any plan to update to  "log4js" to  "1.1.0" ？  

When I use
```
log4js.configure(GConfig.log4jsConfig, { reloadSecs: 300 })
```

got warning :
WARN] log4js - Ignoring configuration reload parameter for "object" configuration.

### PR DESCRIPTION
**Pull request by SunilWang**
fix  #7 
[https://github.com/dominhhai/koa-log4js/issues/7](url)

log4js to 2.3.x
testing OK！

testing code:

```js
const log4 = require('./');
const Koa = require('koa');
const app = Koa();
const appenders = {
  out: {
    type: 'console',
    layout: {
      type: 'pattern',
      pattern: '%[[%d{MM-dd hh:mm:ss SSS} %p ] %c -%] %m%n',
    },
  },
  koajs_test: {
    type: 'dateFile',
    filename: './logs/koajs_test.log',
    pattern: '.yyyyMMddhhmm',
    keepFileExt: true,
    daysToKeep: 120,
    layout: {
      type: 'pattern',
      pattern: '[%d{MM-dd hh:mm:ss SSS} %p ] %c - %m%n',
    },
  },
};


log4.configure({
  appenders: appenders,
  categories: {
    default: { appenders: [ 'out' ], level: 'info' },
    koajs_test: { appenders: [ 'koajs_test', 'out' ], level: 'info' },
  },
});

const logger = log4.getLogger('koajs_test');

app.use(
  log4.koaLogger(
    logger,
    {
      level: 'info',
      format: ':remote-addr - -' +
      ' ":method :url HTTP/:http-version"' +
      ' :status :content-length ":referrer"' +
      ' ":user-agent" ":response-time" | :logStr',
      tokens: [
        {
          token: ':logStr',
          content: function (ctx) {
            return 'logStr';
          },
        },
      ],
    })
);
app.use(function * (next) {
  if (this.request.path === '/') {
    logger.info('testint koa-log4');
  }
  this.body = 'Hello World';
});

app.listen(8000);
```

logout:

```
[11-17 19:06:27 404 INFO ] koajs_test - testint koa-log4

[11-17 19:06:27 415 INFO ] koajs_test - ::1 - - "GET / HTTP/1.1" 200 11 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36" "10" | logStr

[11-17 19:06:27 548 INFO ] koajs_test - ::1 - - "GET /favicon.ico HTTP/1.1" 200 11 "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36" "1" | logStr

```

### CODE REVIEW

**Comment by dominhhai** [comment]
nice job!
Thank you!

**Comment by SunilWang** [comment]
@dominhhai 
Don't mention it.

**Comment by dominhhai** [comment]
Can you upgrade for v2.x too?

**Comment by SunilWang** [comment]
@dominhhai 

OK。

upgrade tomorrow.

**Comment by dominhhai** [comment]
Just land on NPM!

**Pull request merged**
